language: objective-c
 
branches:
 only:
 - master
 
xcode_project: evernote.xcodeproj
xcode_scheme: evernoteTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3 
 
script:
- xcodebuild clean build test -project evernote.xcodeproj -scheme evernoteTests
