language: objective-c

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build -project evernote.xcodeproj -scheme evernoteRelease
- xctool test -project evernote.xcodeproj -scheme evernoteTests
